<?php
$slideGroups = [
    [
        'group' => 'Yireo on Magento',
        'style' => 'yireo',
        'slides' => [
            ['file' => 'yireo/m2s_uicomponents', 'title' => 'Magento 2 KnockoutJS & RequireJS in 1 component'],
            ['file' => 'yireo/running_m2', 'title' => 'Running Magento 2 (Magento Developers Paradise 2016)', 'public' => 1],
            ['file' => 'yireo/leercurves', 'title' => 'Yireo Educatie - Leren samen met Yireo'],
        ],
    ],
    [
        'group' => 'MeetMagento',
        'style' => 'meetmagento',
        'slides' => [
            ['file' => 'yireo/js_testing', 'title' => 'What to test in JS (MageConf 2017 Ukraine)', 'style' => 'mageconf', 'renderer' => 'reveal'],
            ['file' => 'yireo/pwa_is_the_end', 'title' => 'PWA: Is this the end? (ChristMage 2017 Aachen)'],
            ['file' => 'yireo/messing_up_di', 'title' => 'Messing Up DI (MeetMagento 2017 Belgium)'],
            ['file' => 'yireo/m2_linking-components', 'title' => 'M2 Linking JS Components (MeetMagento 2017 Poland)'],
            ['file' => 'yireo/m2_private_content', 'title' => 'M2 Private Data via JS Components (MeetMagento 2017 Netherlands)'],
            ['file' => 'yireo/imagine2017_en', 'title' => 'Imagine 2017 review (EN)'],
            ['file' => 'yireo/m2_for-all-of-us', 'title' => 'Magento 2 - for all of us', 'footer' => 0, 'header' => 0],
        ],
    ],
    [
        'group' => 'MUG - Magento User Group',
        'style' => 'mug',
        'slides' => [
            ['file' => 'mug/waalwijk/news', 'title' => 'MUG Waalwijk introduction'],
            ['file' => 'mug/buckaroo/news', 'title' => 'MUG Utrecht introduction'],
            ['file' => 'mug/localisation/main', 'title' => 'Localisatie'],
            ['file' => 'mug/security/security', 'title' => 'Security'],
            ['file' => 'yireo/magento_layoutphtml', 'title' => 'Magento XML and PHTML', 'style' => 'yireo'],
            ['file' => 'mug/generic/intro', 'title' => 'Introductie tot MUGs'],
            ['file' => 'mug/magento2/plugins', 'title' => 'Magento 2 Plugins and AOP'],
            ['file' => 'mug/magento2/overview', 'title' => 'Overview Magento 2'],
            ['file' => 'mug/quality/quality', 'title' => 'Quality Assurance'],
            ['file' => 'mug/configurables/code', 'title' => 'Configurable Products Code'],
            ['file' => 'mug/magerun/magerun', 'title' => 'n98-magerun'],
            ['file' => 'mug/composer/composer', 'title' => 'Composer &amp; Packagist'],
            ['file' => 'mug/xml/intro', 'title' => 'Magento XML Introduction'],
            ['file' => 'mug/xml/layout', 'title' => 'Layout XML'],
            ['file' => 'mug/xml/magento2', 'title' => 'Magento 2 XML'],
        ],
    ],
    [
        'group' => 'Yireo on Joomla',
        'style' => 'yireo',
        'slides' => [
            ['file' => 'yireo/joomla_composer', 'title' => 'Composer in eigen Joomla projecten (JD18NL)'],
            ['file' => 'yireo/joomla_jep', 'title' => 'Joomla Educatie Project'],
            ['file' => 'yireo/joomla_namespaces', 'title' => 'Implementing namespaces in Joomla (JD17NL)'],
            ['file' => 'yireo/joomla_plugins_workshop', 'title' => 'Joomla Plugins Workshop (JWC16)'],
            ['file' => 'yireo/joomla_hikashop', 'title' => 'Joomla, HikaShop and Yireo'],
            ['file' => 'yireo/joomla_zray', 'title' => 'Zend Z-Ray and Joomla (JAB16)'],
            ['file' => 'yireo/modern_php_in_joomla', 'title' => 'Modern PHP in Joomla (JAB16)'],
            ['file' => 'yireo/php7', 'title' => 'PHP 7 (JoomlaDagen 2016)', 'public' => 1],
            ['file' => 'yireo/plugin_patterns', 'title' => 'Joomla Plugin Concepten (JUG Utrecht)'],
            ['file' => 'yireo/joomla_stuff', 'title' => 'Joomla Stuff (JUG Breda)'],
            ['file' => 'yireo/custom_plugin_jwc15', 'title' => 'Joomla System Plugin Per Project (JWC15)'],
            ['file' => 'yireo/custom_plugin', 'title' => 'Joomla System Plugin Per Project (NL)'],
            ['file' => 'yireo/plugins', 'title' => 'Introducie tot Joomla Plugins &amp; Events (NL)'],
            ['file' => 'yireo/ssl', 'title' => 'Joomla &amp; SSL'],
            ['file' => 'yireo/zray_design', 'title' => 'Joomla &amp; Zend Server Z-Ray - Templaters Aid'],
            ['file' => 'yireo/zray_plugins', 'title' => 'Joomla &amp; Zend Server Z-Ray - Plugins and Events'],
        ],
    ],
    [
        'group' => 'DJPD - Dutch Joomla PHP Developers',
        'style' => 'djpdnl',
        'slides' => [
            ['file' => 'djpd/composer/composer', 'title' => 'Composer'],
            ['file' => 'djpd/automation/phing', 'title' => 'Automation Tools - Phing'],
            ['file' => 'djpd/automation/grunt', 'title' => 'Automation Tools - Grunt'],
            ['file' => 'djpd/automation/gulp', 'title' => 'Automation Tools - Gulp'],
            ['file' => 'djpd/automation/yireo', 'title' => 'Automation Tools - Yireo mojo'],
        ],
    ],
    [
        'group' => 'Joomla Community',
        'style' => 'joomla',
        'slides' => [
        ],
    ],
];
