<?php
$slideGroups = [
    [
        'group' => 'Magento events',
        'style' => 'meetmagento',
        'slides' => [
            ['file' => 'yireo/react_to_ko', 'title' => 'Adding React components to current Knockout frontend (MageTitans UK 2018)', 'style' => 'magetitans-uk', 'renderer' => 'reveal'],
            ['file' => 'yireo/extdn_practices', 'style' => 'extdn', 'title' => 'Extension Best Practices (according to ExtDN)'],
            ['file' => 'yireo/js_testing2', 'title' => 'What to test in JS (MeetMagento Germany 2018)', 'style' => 'mm18de', 'renderer' => 'reveal'],
            ['file' => 'yireo/graphql_react', 'title' => 'Connecting GraphQL (MeetMagento HR 2018', 'style' => 'mm18uk', 'renderer' => 'reveal'],
            ['file' => 'yireo/js_testing', 'title' => 'What to test in JS (MeetMagento Italy 2018)', 'style' => 'mm18it', 'renderer' => 'reveal'],
            ['file' => 'yireo/pwa_is_the_end', 'title' => 'PWA: Is this the end? (ChristMage 2017 Aachen)'],
            ['file' => 'yireo/messing_up_di', 'title' => 'Messing Up DI (MeetMagento 2017 Belgium)'],
            ['file' => 'yireo/m2_linking-components', 'title' => 'M2 Linking JS Components (MeetMagento 2017 Poland)'],
            ['file' => 'yireo/m2_private_content', 'title' => 'M2 Private Data via JS Components (MeetMagento 2017 Netherlands)'],
            ['file' => 'yireo/imagine2017_en', 'title' => 'Imagine 2017 review (EN)'],
            ['file' => 'yireo/m2_for-all-of-us', 'title' => 'Magento 2 - for all of us', 'footer' => 0, 'header' => 0],
            ['file' => 'yireo/m2s_uicomponents', 'title' => 'Magento 2 KnockoutJS & RequireJS in 1 component'],
            ['file' => 'yireo/running_m2', 'title' => 'Running Magento 2 (Magento Developers Paradise 2016)', 'public' => 1],
        ],
    ],
    [
        'group' => 'Magento User Groups',
        'style' => 'mug',
        'slides' => [
            ['file' => 'mug/zurich/pwa', 'title' => 'Magento Meetup Zurich PWA'],
            ['file' => 'mug/waalwijk/codeception', 'title' => 'MUG Waalwijk - Codeception'],
            ['file' => 'mug/waalwijk/news', 'title' => 'MUG Waalwijk introduction'],
            ['file' => 'mug/buckaroo/news', 'title' => 'MUG Utrecht introduction'],
            ['file' => 'mug/localisation/main', 'title' => 'Localisatie'],
            ['file' => 'mug/security/security', 'title' => 'Security'],
            ['file' => 'yireo/magento_layoutphtml', 'title' => 'Magento XML and PHTML', 'style' => 'yireo'],
            ['file' => 'mug/generic/intro', 'title' => 'Introductie tot MUGs'],
            ['file' => 'mug/magento2/plugins', 'title' => 'Magento 2 Plugins and AOP'],
            ['file' => 'mug/magento2/overview', 'title' => 'Overview Magento 2'],
            ['file' => 'mug/quality/quality', 'title' => 'Quality Assurance'],
            ['file' => 'mug/configurables/code', 'title' => 'Configurable Products Code'],
            ['file' => 'mug/magerun/magerun', 'title' => 'n98-magerun'],
            ['file' => 'mug/composer/composer', 'title' => 'Composer &amp; Packagist'],
            ['file' => 'mug/xml/intro', 'title' => 'Magento XML Introduction'],
            ['file' => 'mug/xml/layout', 'title' => 'Layout XML'],
            ['file' => 'mug/xml/magento2', 'title' => 'Magento 2 XML'],
        ],
    ],
];
