<?php
$slideGroups = array(
    array(
        'group' => 'Yireo on Joomla and Magento',
        'style' => 'yireo',
        'slides' => array(
            array('file' => 'yireo/m2s_uicomponents', 'title' => 'Magento 2 KnockoutJS & RequireJS in 1 component (M2Seminar v2)'),
            array('file' => 'yireo/m2_for-all-of-us', 'title' => 'Magento 2 - for all of us', 'footer' => 0, 'header' => 0),
            array('file' => 'yireo/joomla_hikashop', 'title' => 'Joomla, HikaShop and Yireo'),
            array('file' => 'yireo/joomla_zray', 'title' => 'Zend Z-Ray and Joomla (JAB16)'),
            array('file' => 'yireo/modern_php_in_joomla', 'title' => 'Modern PHP in Joomla (JAB16)'),
            array('file' => 'yireo/running_m2', 'title' => 'Running Magento 2 (Magento Developers Paradise 2016)', 'public' => 1),
            array('file' => 'yireo/messing_up_di', 'title' => 'Messing Up DI (MeetMagento NL 2016)', 'public' => 1),
            array('file' => 'yireo/php7', 'title' => 'PHP 7 (JoomlaDagen 2016)', 'public' => 1),
            array('file' => 'yireo/plugin_patterns', 'title' => 'Joomla Plugin Concepten (JUG Utrecht)'),
            array('file' => 'yireo/joomla_stuff', 'title' => 'Joomla Stuff (JUG Breda)'),
            array('file' => 'yireo/custom_plugin_jwc15', 'title' => 'Joomla System Plugin Per Project (JWC15)'),
            array('file' => 'yireo/custom_plugin', 'title' => 'Joomla System Plugin Per Project (NL)'),
            array('file' => 'yireo/plugins', 'title' => 'Introducie tot Joomla Plugins &amp; Events (NL)'),
            array('file' => 'yireo/ssl', 'title' => 'Joomla &amp; SSL'),
            array('file' => 'yireo/zray_design', 'title' => 'Joomla &amp; Zend Server Z-Ray - Templaters Aid'),
            array('file' => 'yireo/zray_plugins', 'title' => 'Joomla &amp; Zend Server Z-Ray - Plugins and Events'),
            array('file' => 'yireo/leercurves', 'title' => 'Yireo Educatie - Leren samen met Yireo'),
        ),
    ),
    array(
        'group' => 'MUG - Magento User Group',
        'style' => 'mug',
        'slides' => array(
            array('file' => 'mug/localisation/main', 'title' => 'Localisatie'),
            array('file' => 'mug/security/security', 'title' => 'Security'),
            array('file' => 'yireo/magento_layoutphtml', 'title' => 'Magento XML and PHTML', 'style' => 'yireo'),
            array('file' => 'mug/generic/intro', 'title' => 'Introductie tot MUGs'),
            array('file' => 'mug/magento2/plugins', 'title' => 'Magento 2 Plugins and AOP'),
            array('file' => 'mug/magento2/overview', 'title' => 'Overview Magento 2'),
            array('file' => 'mug/quality/quality', 'title' => 'Quality Assurance'),
            array('file' => 'mug/configurables/code', 'title' => 'Configurable Products Code'),
            array('file' => 'mug/magerun/magerun', 'title' => 'n98-magerun'),
            array('file' => 'mug/composer/composer', 'title' => 'Composer &amp; Packagist'),
            array('file' => 'mug/xml/intro', 'title' => 'Magento XML Introduction'),
            array('file' => 'mug/xml/layout', 'title' => 'Layout XML'),
            array('file' => 'mug/xml/magento2', 'title' => 'Magento 2 XML'),
        ),
    ),
    array(
        'group' => 'DJPD - Dutch Joomla PHP Developers',
        'style' => 'djpdnl',
        'slides' => array(
            array('file' => 'djpd/automation/phing', 'title' => 'Automation Tools - Phing'),
            array('file' => 'djpd/automation/grunt', 'title' => 'Automation Tools - Grunt'),
            array('file' => 'djpd/automation/gulp', 'title' => 'Automation Tools - Gulp'),
            array('file' => 'djpd/automation/yireo', 'title' => 'Automation Tools - Yireo mojo'),
        ),
    ),
);
